package org.example.springboot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

//para acessar via http com os arquivos Front-end fora da pasta do projeto
@CrossOrigin(origins = "*")         // Permite requisições de qualquer origem
@Controller	                        // This means that this class is a Controller
@RequestMapping(path="/demo")    // This means URL's start with /demo (after Application path)
public class MainController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserRepository userRepository;

    // Main page
    @GetMapping(path="")
    public String mainPage(){
        return "forward:/pages/Index.html";
    }

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

    @PutMapping(path="/update/{id}")
    public @ResponseBody String updateUser(@PathVariable int id, @RequestParam String name, @RequestParam String email) {
        Optional<User> u = userRepository.findById(id);
        if (u.isPresent()) {
            User m =  u.get();
            m.setName(name);
            m.setEmail(email);
            userRepository.save(m);
            return "Updated";
        }
        return "User not found";
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody String deleteUser(@PathVariable int id) {
        Optional<User> u = userRepository.findById(id);
        if (u.isPresent()) {
            userRepository.delete(u.get());
            return "Deleted";
        }
        return "User not found";
    }

    @GetMapping("/test")
    public @ResponseBody String test() {
        try {
            // Test database connection
            long userCount = userRepository.count();

            // Test if we can save a user
            User testUser = new User();
            testUser.setName("Test User");
            testUser.setEmail("test@example.com");
            userRepository.save(testUser);

            return "SUCCESS: Database connected! User count: " + userCount +
                    ". Test user saved with ID: " + testUser.getId();
        } catch (Exception e) {
            return "ERROR: " + e.getMessage();
        }
    }

}
